# SPDX-FileCopyrightText: reass <https://github.com/reassDev>
# SPDX-License-Identifier: CC-BY-4.0

version = 1

[[annotations]]
path = ["*.jpg", "*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "reass <https://github.com/reassDev>"
SPDX-License-Identifier = "CC-BY-4.0"

# Font from: https://fonts.google.com/specimen/Space+Grotesk
[[annotations]]
path = ["SpaceGrotesk-Bold.otf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright 2020 The Space Grotesk Project Authors (https://github.com/floriankarsten/space-grotesk)"
SPDX-License-Identifier = "OFL-1.1"